-- liquibase formatted sql

-- changeset minen:1700080749857-1
CREATE TABLE "application" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "application_status" VARCHAR(255), "creation_date" TIMESTAMP WITHOUT TIME ZONE, "deadline_date" TIMESTAMP WITHOUT TIME ZONE, "name" VARCHAR(255), "record_state" VARCHAR(255), "result_date" TIMESTAMP WITHOUT TIME ZONE, "creator_id" BIGINT, "document_id" BIGINT, CONSTRAINT "application_pkey" PRIMARY KEY ("id"));

-- changeset minen:1700080749857-2
CREATE TABLE "application_item" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "comment" VARCHAR(255), "create_time" TIMESTAMP WITHOUT TIME ZONE, "record_state" VARCHAR(255), "status" VARCHAR(255), "vote_time" TIMESTAMP WITHOUT TIME ZONE, "application_id" BIGINT, "department_id" BIGINT, "user_id" BIGINT, CONSTRAINT "application_item_pkey" PRIMARY KEY ("id"));

-- changeset minen:1700080749857-3
CREATE TABLE "auth_user_info" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "email" VARCHAR(255), "password" VARCHAR(255), "user_id" BIGINT, CONSTRAINT "auth_user_info_pkey" PRIMARY KEY ("id"));

-- changeset minen:1700080749857-4
CREATE TABLE "department" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR(255), "record_state" VARCHAR(255), "serial_key" VARCHAR(255), CONSTRAINT "department_pkey" PRIMARY KEY ("id"));

-- changeset minen:1700080749857-5
CREATE TABLE "document" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "creation_date" TIMESTAMP WITHOUT TIME ZONE, "name" VARCHAR(255), "record_state" VARCHAR(255), "update_date" TIMESTAMP WITHOUT TIME ZONE, "application_id" BIGINT, "user_id" BIGINT, "document_constructor_type_id" BIGINT, CONSTRAINT "document_pkey" PRIMARY KEY ("id"));

-- changeset minen:1700080749857-6
CREATE TABLE "document_constructor_type" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR(255), "prefix" VARCHAR(255), "record_state" VARCHAR(255), CONSTRAINT "document_constructor_type_pkey" PRIMARY KEY ("id"));

-- changeset minen:1700080749857-7
CREATE TABLE "field" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR(255), "document_constructor_type_id" BIGINT, CONSTRAINT "field_pkey" PRIMARY KEY ("id"));

-- changeset minen:1700080749857-8
CREATE TABLE "file" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR(255), "path" VARCHAR(255), "size" BIGINT, "type" VARCHAR(255), "document_id" BIGINT, CONSTRAINT "file_pkey" PRIMARY KEY ("id"));

-- changeset minen:1700080749857-9
CREATE TABLE "personal_user_info" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "birth_date" date, "first_name" VARCHAR(255), "last_name" VARCHAR(255), "patronymic" VARCHAR(255), "user_id" BIGINT, CONSTRAINT "personal_user_info_pkey" PRIMARY KEY ("id"));

-- changeset minen:1700080749857-10
CREATE TABLE "roles" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR(255), CONSTRAINT "roles_pkey" PRIMARY KEY ("id"));

-- changeset minen:1700080749857-11
CREATE TABLE "users" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "position" VARCHAR(255), "record_state" VARCHAR(255), "username" VARCHAR(255), "department_id" BIGINT, CONSTRAINT "users_pkey" PRIMARY KEY ("id"));

-- changeset minen:1700080749857-12
ALTER TABLE "department" ADD CONSTRAINT "uk_gkrfp4eq0fpuprjhcfr6ebepa" UNIQUE ("serial_key");

-- changeset minen:1700080749857-13
ALTER TABLE "document_constructor_type" ADD CONSTRAINT "uk_hn3pboxeicghr1yr5fjdpkxgb" UNIQUE ("name");

-- changeset minen:1700080749857-14
ALTER TABLE "users" ADD CONSTRAINT "uk_r43af9ap4edm43mmtq01oddj6" UNIQUE ("username");

-- changeset minen:1700080749857-15
CREATE TABLE "document_field_value" ("document_id" BIGINT NOT NULL, "value" VARCHAR(255), "field_id" BIGINT NOT NULL, CONSTRAINT "document_field_value_pkey" PRIMARY KEY ("document_id", "field_id"));

-- changeset minen:1700080749857-16
CREATE TABLE "users_roles" ("user_id" BIGINT NOT NULL, "roles_id" INTEGER NOT NULL);

-- changeset minen:1700080749857-17
ALTER TABLE "application_item" ADD CONSTRAINT "fk2kbwiy41en330c4g2klf5k8cp" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset minen:1700080749857-18
ALTER TABLE "users_roles" ADD CONSTRAINT "fk2o0jvgh89lemvvo17cbqvdxaa" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset minen:1700080749857-19
ALTER TABLE "document" ADD CONSTRAINT "fk44725n9linud4cn2b1rsmavia" FOREIGN KEY ("application_id") REFERENCES "application" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset minen:1700080749857-20
ALTER TABLE "application_item" ADD CONSTRAINT "fk6bx6cfj8x3j56iyx29xuo04pg" FOREIGN KEY ("department_id") REFERENCES "department" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset minen:1700080749857-21
ALTER TABLE "field" ADD CONSTRAINT "fk9lltoi3ln21d8vwdtqtsh0hip" FOREIGN KEY ("document_constructor_type_id") REFERENCES "document_constructor_type" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset minen:1700080749857-22
ALTER TABLE "users_roles" ADD CONSTRAINT "fka62j07k5mhgifpp955h37ponj" FOREIGN KEY ("roles_id") REFERENCES "roles" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset minen:1700080749857-23
ALTER TABLE "application_item" ADD CONSTRAINT "fkctur2ak1b9qdajbydimjuhtui" FOREIGN KEY ("application_id") REFERENCES "application" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset minen:1700080749857-24
ALTER TABLE "users" ADD CONSTRAINT "fkfi832e3qv89fq376fuh8920y4" FOREIGN KEY ("department_id") REFERENCES "department" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset minen:1700080749857-25
ALTER TABLE "application" ADD CONSTRAINT "fki95jn4ckqwei6b60ul2i4guqa" FOREIGN KEY ("document_id") REFERENCES "document" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset minen:1700080749857-26
ALTER TABLE "application" ADD CONSTRAINT "fkisve5ylfrsd9grn23dsjobldx" FOREIGN KEY ("creator_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset minen:1700080749857-27
ALTER TABLE "document" ADD CONSTRAINT "fkjj68k88ipvowy4iyp6u0hmhto" FOREIGN KEY ("document_constructor_type_id") REFERENCES "document_constructor_type" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset minen:1700080749857-28
ALTER TABLE "document" ADD CONSTRAINT "fkm19xjdnh3l6aueyrpm1705t52" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset minen:1700080749857-29
ALTER TABLE "document_field_value" ADD CONSTRAINT "fkmknk9ujo0crfl7ra3h317224q" FOREIGN KEY ("field_id") REFERENCES "field" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset minen:1700080749857-30
ALTER TABLE "document_field_value" ADD CONSTRAINT "fkp8w74cynljpis1wmw1r6es8nd" FOREIGN KEY ("document_id") REFERENCES "document" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset minen:1700080749857-31
ALTER TABLE "file" ADD CONSTRAINT "fkqo5bd7l92rst6ysfqvep4uitu" FOREIGN KEY ("document_id") REFERENCES "document" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset minen:1700080749857-32
ALTER TABLE "auth_user_info" ADD CONSTRAINT "fkqy9huojykj3ny3cij36a8i3ko" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset minen:1700080749857-33
ALTER TABLE "personal_user_info" ADD CONSTRAINT "fkrxeurxh5pjpn92a98owxd2lj0" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

