@startuml

actor "Frontend" as front

box "Backend" #Lightgreen
control "DocumentConstructorTypeController" as controller
participant "DocumentConstructorTypeService" as service
database "Database" as db
end box

autonumber

front -> controller++: POST /api/doctype/
controller -> controller: Check user role
alt "User has ADMIN role"
    controller -> controller: Validate request
    alt "Request is valid"
        controller -> service++: createDocumentConstructorType()
        service -> db++: saveDocumentConstructorType()
        db -> db: Check unique name constraint
        alt "Name is unique"
            db --> service: Saved entity
            service --> controller: Saved document type
            controller --> front: 201: Created document type
        else "Name isn't unique"
            db --> service--: error: unique constraint violation
            service --> controller--: Exception
            controller --> front: 422: Document type with the \n specified name already exists
        end
    else "Request is invalid"
        controller --> front: 400: Bad request
    end
else "User doesn't have ADMIN role""
    controller --> front--: 401: User doesn't have ADMIN role
end

@enduml