@startuml

actor "Frontend" as front

box "Backend" #Lightgreen
control "DepartmentController" as controller
participant "DepartmentService" as service
database "Database" as db
end box

'autonumber

front -> controller++: POST /api/department/
controller -> controller: Check user role
alt "User has ADMIN role"
    controller -> controller: Validate request
    alt "Request is valid"
        controller -> service++: createDepartment()
        service -> db++: saveDepartment()
        db -> db: Check valid
        alt "Create"
            db --> service: Saved entity
            service --> controller: Saved Department
            controller --> front: 201: Created Department
        else
            db --> service--: error: validation problems
            service --> controller--: Exception
            controller --> front: 422:Department with the \n specified name  SQL Validation exception
        end
    else "Request is invalid"
        controller --> front: 400: Bad request
    end
else "User doesn't have ADMIN role""
    controller --> front--: 403: "Access denied"
end

@enduml