@startuml

actor "Frontend" as front

box "Backend" #Lightgreen
control "DepartmentController" as controller
participant "DepartmentService" as service
database "Database" as db
end box

'autonumber

front -> controller++: GET /api/department/
controller -> controller: Check user role
alt "User has any role"
        alt "Request is valid"
        controller -> service++: getAllDepartmentsPageByPage(PageRequest.of(page, limit), name, recordState)
        service -> db++: findDepartmentsByNameContainingAndRecordState(name, pageable, recordState)
        db --> service--: Got a page of Departments
        service --> controller--: Converted a page to a list
            alt "Database has such Department"
                controller --> front: 200: Page with Departments found
            else "Database doesn't have such Department"
                controller --> front: 204: Page with Departments not found
            end
        else "Request is not valid"
            controller --> front: 400: Invalid request parameter (parameters)
        end
else "User doesn't have any role"
    controller -> front--: 401: User is not authenticated
end

@enduml
