@startuml

actor "Frontend" as front

box "Backend" #Lightgreen
control "DepartmentController" as controller
participant "DepartmentService" as service
database "Database" as db
end box

'autonumber

front -> controller++: PUT /api/department/{id}
controller -> controller: Check user role
alt "User has ADMIN role"
    controller -> controller: Validate request
    alt "Request is valid"
        controller -> service++: updateName(id, departmentRequestDto)
        service -> db++: findById(id)
        alt "Department found"
            db --> service: Department
            service -> service: Set new Department name
            alt "New Department name"
                service -> db: save(Department)
                db --> service: Updated Department
                service --> controller: Success
                controller --> front: 200: Department updated
            else
                db --> service: Error: validation problems
                service --> controller: Exception
                controller --> front: 422: Department with the \n specified name  SQL Validation exception
            end
        else "Department is not found"
            db --> service--: Empty result
            service --> controller--: Error: Department not found
            controller --> front: 404: Department isn't found
        end
    else "Request is invalid"
        controller --> front: 400: Invalid request body or path variable
    end
else "User doesn't have ADMIN role""
    controller --> front--: 403: "Access denied"
end

@enduml